#
# Module manifest for module 'PSNVIDIA.NLS'
#
# Generated by: hitechcloud-vietnam
#
# Generated on: 14.06.2025
#

@{
    RootModule = 'PSNVIDIA.NLS.psm1'

    ModuleVersion = '0.2506.1'

    CompatiblePSEditions = @('Core', 'Desktop')

    GUID = '47d863db-5ec1-4308-98d7-e949ced83692'

    Author = 'hitechcloud-vietnam'

    Copyright = 'Copyright (c) 2025 hitechcloud-vietnam, licensed under the MIT License.'

    Description = 'A PowerShell module for interacting with the NVIDIA License System API.'

    PowerShellVersion = '5.1'

    FunctionsToExport = @('Get-NVLSCompatibleDownload', 'Find-NVLSDownload')

    PrivateData = @{
        PSData = @{
            Tags = @(
                'NVIDIA', 'PowerShell', 'PowerShell-Core', 'PowerShell-Desktop', 'vGPU'
            )

            ProjectUri     = 'https://github.com/hitechcloud-vietnam/PSNVIDIA.NLS'
            License        = 'https://github.com/hitechcloud-vietnam/PSNVIDIA.NLS/blob/main/LICENSE'
            ReleaseNotes   = 'https://github.com/hitechcloud-vietnam/PSNVIDIA.NLS'
        }
    }
}
